### ISSUE TITLE
Allow comments to be preserved in place when merging YAML

### ISSUE THREAD

**Issue by vividviolet** [Shopify/shopify-cli-extensions#121]

**Comment by t6d** [comment]
@vividviolet, how vital is this? This might be a lot tricker than it looks like. The parser might simply ignore comments all together. If not absolutely required, I'd close this issue.

**Comment by vividviolet** [comment]
This is not vital until we have complicated comments inside our YAML files. Currently all we need to support is metafields which already works using the simple merge. Ex. 
```yml
---
development:
  build_dir: build
  entries:
    main: src/index.tsx
# metafields:
#   - namespace: my-namespace
#     key: my-key
#   - namespace: my-namespace
#     key: my-key-2
```

I'll close this issue
