### ISSUE TITLE
Entrypoint configuration

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-cli-extensions#210]
Users should not be expected to manually configure entry points. This should be a documented expert setting instead. Hence, `development > entries` should be removed from `extension.config.yml` for now. As a first step, we can default to `build/main.js` to be produced from `src/index.[jt]sx?`, later individual extension points could choose to configure modules differently. With `build_dir` already defaulting to `build` we can remove the entire development section from the persisted configuration:

```yaml
development: # <-- entire tree should be generated on the fly be the Ruby layer
  entries:
    main: src/index.ts
    build_dir: build # <-- already removed
extension_points:
  - Checkout::Feature::Render
# metafields:
#   - namespace: my-namespace
#     key: my-key
#   - namespace: my-namespace
#     key: my-key-2
```

- [x] Ensure that the `shopify-cli` (Ruby) correctly sets a default value for the `main` entry point
- [x] Remove persisting the `main` entry point from the extension templates in `shopify-cli-extensions/create`
