### ISSUE TITLE
Cannot set dynamic port, public URL, and store

### ISSUE THREAD

**Issue by kumar303** [Shopify/shopify-cli-extensions#262]
I'm trying to run `shopify-cli-extensions` in Shopify's Spin tool which is similar to any cloud based hosting solution. It requires setting a dynamic port, public URL, and store domain.

Is this possible? I can't get it to work but I maybe missing something. Here's an idea of what I probably want to do (not 100% sure) in my `extension.config.yml`:

```yaml
---
port: $PORT
public_url: https://$SPIN_INSTANCE_FQDN
store: shop1.$SPIN_SHOPIFY_SERVICE_FQDN

extensions:
  - title: Extension name
    extension_points:
    - Checkout::Feature::Render
    development:
      resource:
        url: 'cart/1234'
```

When I run `shopify-cli-extensions develop`, nothing happens (no output).
