### ISSUE TITLE
Environment variables are not propagated

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-cli-extensions#275]
Environment variables in the `extension.config.yml` file are not propagated to the JavaScript layer. This should be fixed and the integration test expanded to grep for these values so this doesn't regress again.

```
---
extension_points:
  - Playground
metafields:
  - namespace: my-namespace
    key: my-key
development:
  build:
    env:
      CUSTOM_VAR: bar
  develop:
    env:
      CUSTOM_VAR: foo
```

- [x] Ensure that the Go layer properly serializes the extension configuration before passing it to the JS layer
- [x] Ensure that the JS layer consumes the environment settings correctly
