### ISSUE TITLE
Agree on shape of shopifile.yml

### ISSUE THREAD

**Issue by cecyc** [Shopify/shopify-cli-extensions#49]
Purpose: We are proposing a new file to be the source of truth for extension development on the `shopify-cli`. This would **NOT** replace the `shopify-cli.yml` file, but would simply serve as a standardize way to persist the data extensions currently need in order to perform certain tasks. This format could, in the future, extend to support other types of CLI projects, such as apps and themes, but that is TBD.

Proposed shape:

```yml
extensions:
  - uuid: 00000000-0000-0000-0000-000000000000
    type: checkout_ui_extension
    user:
      metafields: []
    development:
      root_dir: "some_dir"
      build_dir: "build"
      template: "typescript-react"
      renderer:
        name: "@shopify/checkout-ui-extensions"

apps: ...

themes: ...

scripts: ...
version: "1"
```
